// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wqwyvsfitjabvdfofkna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indxd3l2c2ZpdGphYnZkZm9ma25hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0ODQwNDEsImV4cCI6MjA3NDA2MDA0MX0.fb7vODrXpeFJI3UDjPVskV43U41JBee---L_NeddUvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);